"""initial schema

Revision ID: dc538d6a653b
Revises:
Create Date: 2025-12-11 13:29:14.279247
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc538d6a653b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("observatory_name", sa.String(length=255), nullable=False),
        sa.Column("source", sa.String(length=255), nullable=False),
        sa.Column("schedule_start", sa.DateTime(), nullable=False),
        sa.Column("schedule_end", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_schedules_id"), "schedules", ["id"], unique=False)
    op.create_index(
        op.f("ix_schedules_observatory_name"),
        "schedules",
        ["observatory_name"],
        unique=True,
    )
    op.create_table(
        "observations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("schedule_id", sa.Integer(), nullable=True),
        sa.Column("observatory_name", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("SCHEDULED", "ARCHIVED", name="observationstatus"),
            nullable=False,
        ),
        sa.Column("target_name", sa.String(length=255), nullable=True),
        sa.Column("ra", sa.Float(), nullable=True),
        sa.Column("dec", sa.Float(), nullable=True),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("fov_radius", sa.Float(), nullable=True),
        sa.Column("on_sky_angle", sa.Float(), nullable=True),
        sa.Column("instrument", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedules.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_observations_id"), "observations", ["id"], unique=False)
    op.create_index(
        op.f("ix_observations_observatory_name"),
        "observations",
        ["observatory_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observations_start_time"), "observations", ["start_time"], unique=False
    )
    op.create_index(
        op.f("ix_observations_status"), "observations", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_observations_target_name"),
        "observations",
        ["target_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_observations_target_name"), table_name="observations")
    op.drop_index(op.f("ix_observations_status"), table_name="observations")
    op.drop_index(op.f("ix_observations_start_time"), table_name="observations")
    op.drop_index(op.f("ix_observations_observatory_name"), table_name="observations")
    op.drop_index(op.f("ix_observations_id"), table_name="observations")
    op.drop_table("observations")
    op.drop_index(op.f("ix_schedules_observatory_name"), table_name="schedules")
    op.drop_index(op.f("ix_schedules_id"), table_name="schedules")
    op.drop_table("schedules")
    # ### end Alembic commands ###
