"""add observatory location

Revision ID: 50d0abb42d56
Revises: 99ca4f6696a7
Create Date: 2025-12-18 11:10:04.420280
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "50d0abb42d56"
down_revision: str | None = "99ca4f6696a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedules",
        sa.Column(
            "observatory_latitude", sa.Float(), nullable=False, server_default="0.0"
        ),
    )
    op.add_column(
        "schedules",
        sa.Column(
            "observatory_longitude", sa.Float(), nullable=False, server_default="0.0"
        ),
    )
    op.add_column(
        "schedules",
        sa.Column(
            "observatory_elevation", sa.Float(), nullable=False, server_default="0.0"
        ),
    )

    op.alter_column("schedules", "observatory_latitude", server_default=None)
    op.alter_column("schedules", "observatory_longitude", server_default=None)
    op.alter_column("schedules", "observatory_elevation", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedules", "observatory_elevation")
    op.drop_column("schedules", "observatory_longitude")
    op.drop_column("schedules", "observatory_latitude")
    # ### end Alembic commands ###
